/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Install;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Installer extends javax.swing.JFrame {
    int n;
    /**
     * Creates new form Installer
     */
    public Installer() {
        n=1;
        initComponents();
        cancel.setText("Cancel");
        next.setText("Next");
        back.setVisible(false);
        
        Page1.setVisible(true);
        Page2.setVisible(false);
        Page3.setVisible(false);
        Page4.setVisible(false);
        Page5.setVisible(false);
        
        jCheckBoxMysql.setSelected(true);
        jCheckBoxEJ.setSelected(true);
        jCheckBoxJDK.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PageButton = new javax.swing.JLayeredPane();
        cancel = new javax.swing.JButton();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Page1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Page2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxEJ = new javax.swing.JCheckBox();
        jCheckBoxJDK = new javax.swing.JCheckBox();
        jCheckBoxMysql = new javax.swing.JCheckBox();
        Page3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Page4 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        Page5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Engineering Journal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cancel.setText("jButton1");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        cancel.setBounds(350, 10, 73, 23);
        PageButton.add(cancel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        next.setText("jButton2");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        next.setBounds(260, 10, 73, 23);
        PageButton.add(next, javax.swing.JLayeredPane.DEFAULT_LAYER);

        back.setText("jButton3");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.setBounds(170, 10, 73, 23);
        PageButton.add(back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setForeground(java.awt.Color.gray);
        jLabel3.setText("This wizard will guide you through the installation process ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText(" Welcome to Installation Wizard for Engineering Journal");

        jLabel10.setForeground(java.awt.Color.gray);
        jLabel10.setText("for the Engineering Journal.");

        jLabel11.setForeground(java.awt.Color.gray);
        jLabel11.setText("To contininue, click Next.");

        javax.swing.GroupLayout Page1Layout = new javax.swing.GroupLayout(Page1);
        Page1.setLayout(Page1Layout);
        Page1Layout.setHorizontalGroup(
            Page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(Page1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(Page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(Page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel3)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        Page1Layout.setVerticalGroup(
            Page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(28, 28, 28))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Choose program for install.");

        jCheckBoxEJ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxEJ.setText("   Engineering Journal");
        jCheckBoxEJ.setEnabled(false);
        jCheckBoxEJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEJActionPerformed(evt);
            }
        });

        jCheckBoxJDK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxJDK.setText("   Java SE Development Kit 7");

        jCheckBoxMysql.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxMysql.setText("   MySQL 5.0.51b");

        javax.swing.GroupLayout Page2Layout = new javax.swing.GroupLayout(Page2);
        Page2.setLayout(Page2Layout);
        Page2Layout.setHorizontalGroup(
            Page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(Page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Page2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(Page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxEJ, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxMysql)
                            .addComponent(jCheckBoxJDK, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        Page2Layout.setVerticalGroup(
            Page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Page2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxEJ)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxJDK)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxMysql)
                .addGap(34, 34, 34))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("You choose program for install");

        jLabel7.setText("Engineering Journal");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout Page3Layout = new javax.swing.GroupLayout(Page3);
        Page3.setLayout(Page3Layout);
        Page3Layout.setHorizontalGroup(
            Page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page3Layout.createSequentialGroup()
                .addGroup(Page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Page3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4))
                    .addGroup(Page3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(Page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        Page3Layout.setVerticalGroup(
            Page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Page4Layout = new javax.swing.GroupLayout(Page4);
        Page4.setLayout(Page4Layout);
        Page4Layout.setHorizontalGroup(
            Page4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Page4Layout.setVerticalGroup(
            Page4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Page4Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Welcome to Engineering Journal program.");

        jLabel6.setForeground(java.awt.Color.gray);
        jLabel6.setText("Click finish for close Engineering Journal program.");

        javax.swing.GroupLayout Page5Layout = new javax.swing.GroupLayout(Page5);
        Page5.setLayout(Page5Layout);
        Page5Layout.setHorizontalGroup(
            Page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(Page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Page5Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addGroup(Page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addContainerGap(86, Short.MAX_VALUE)))
        );
        Page5Layout.setVerticalGroup(
            Page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
            .addGroup(Page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Page5Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jLabel5)
                    .addGap(46, 46, 46)
                    .addComponent(jLabel6)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Page1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Page2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Page3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Page4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Page5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(PageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Page1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(70, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Page2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Page3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Page4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Page5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-466)/2, (screenSize.height-338)/2, 466, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        n++;
        System.out.println(n);
        if(n%5 == 1){
            Page1.setVisible(true);
            Page2.setVisible(false);
            Page3.setVisible(false);
            Page4.setVisible(false);
            Page5.setVisible(false);
            
            cancel.setText("Cancel");
            next.setText("Next");
            
            cancel.setVisible(true);
            next.setVisible(true);
            back.setVisible(true);
        }else if(n%5 == 2){
            Page1.setVisible(false);
            Page2.setVisible(true);
            Page3.setVisible(false);
            Page4.setVisible(false);
            Page5.setVisible(false);
            
            cancel.setText("Cancel");
            next.setText("Next");
            back.setText("Back");
            
            cancel.setVisible(true);
            next.setVisible(true);
            back.setVisible(true);
        }else if(n%5 == 3){
            Page1.setVisible(false);
            Page2.setVisible(false);
            Page3.setVisible(true);
            Page4.setVisible(false);
            Page5.setVisible(false);
            
            cancel.setText("Cancel");
            next.setText("Install");
            back.setText("Back");
            
            cancel.setVisible(true);
            next.setVisible(true);
            back.setVisible(true);
            
            if(!jCheckBoxJDK.isSelected() && !jCheckBoxMysql.isSelected()){
                jLabel8.setText("");
                jLabel9.setText("");
            }else if(jCheckBoxJDK.isSelected() && !jCheckBoxMysql.isSelected()){
                jLabel8.setText("Java SE Development Kit 7");
                jLabel9.setText("");
            }else if(!jCheckBoxJDK.isSelected() && jCheckBoxMysql.isSelected()){
                jLabel8.setText("MySQL 5.0.51b");
                jLabel9.setText("");
            }else if(jCheckBoxJDK.isSelected() && jCheckBoxMysql.isSelected()){
                jLabel8.setText("Java SE Development Kit 7");
                jLabel9.setText("MySQL 5.0.51b");
            }
        }else if(n%5 == 4){
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Installer.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Page1.setVisible(false);
            Page2.setVisible(false);
            Page3.setVisible(false);
            Page4.setVisible(true);
            Page5.setVisible(false);
            
            cancel.setVisible(false);
            next.setVisible(false);
            back.setVisible(false);
            if(!jCheckBoxJDK.isSelected() && !jCheckBoxMysql.isSelected()){
                runEXE("setupJournal.exe");
                jProgressBar1.setValue(100);      
            Page1.setVisible(false);
            Page2.setVisible(false);
            Page3.setVisible(false);
            Page4.setVisible(false);
            Page5.setVisible(true);
            
            cancel.setText("Cancel");
            next.setText("Finish");
            back.setText("Back");
            
            cancel.setVisible(false);
            next.setVisible(true);
            back.setVisible(false);
            }else if(jCheckBoxJDK.isSelected() && !jCheckBoxMysql.isSelected()){
                runEXE("jdk-7u9-windows-i586.exe");
                jProgressBar1.setValue(80);
                runEXE("setupJournal.exe");
                jProgressBar1.setValue(100);
             Page1.setVisible(false);
            Page2.setVisible(false);
            Page3.setVisible(false);
            Page4.setVisible(false);
            Page5.setVisible(true);
            
            cancel.setText("Cancel");
            next.setText("Finish");
            back.setText("Back");
            
            cancel.setVisible(false);
            next.setVisible(true);
            back.setVisible(false);
            }else if(!jCheckBoxJDK.isSelected() && jCheckBoxMysql.isSelected()){
                runEXE("mysql-5.0.51b-win32.exe");
                jProgressBar1.setValue(80);
                runEXE("setupJournal.exe");
                jProgressBar1.setValue(100);
             Page1.setVisible(false);
            Page2.setVisible(false);
            Page3.setVisible(false);
            Page4.setVisible(false);
            Page5.setVisible(true);
            
            cancel.setText("Cancel");
            next.setText("Finish");
            back.setText("Back");
            
            cancel.setVisible(false);
            next.setVisible(true);
            back.setVisible(false);
            }else if(jCheckBoxJDK.isSelected() && jCheckBoxMysql.isSelected()){
                runEXE("jdk-7u9-windows-i586.exe");
                jProgressBar1.setValue(40);
                runEXE("mysql-5.0.51b-win32.exe");
                jProgressBar1.setValue(80);
                runEXE("setupJournal.exe");
                jProgressBar1.setValue(100);
                
            Page1.setVisible(false);
            Page2.setVisible(false);
            Page3.setVisible(false);
            Page4.setVisible(false);
            Page5.setVisible(true);
            
            cancel.setText("Cancel");
            next.setText("Finish");
            back.setText("Back");
            
            cancel.setVisible(false);
            next.setVisible(true);
            back.setVisible(false);
            }
            //exit(this);
        }
        else if(n%5 == 0){
            exit(this);
        }
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        n--;
        System.out.println(n);
        if(n%5 == 1){
            Page1.setVisible(true);
            Page2.setVisible(false);
            Page3.setVisible(false);
            Page4.setVisible(false);
            Page5.setVisible(false);
            
            cancel.setText("Cancel");
            next.setText("Next");
            
            cancel.setVisible(true);
            next.setVisible(true);
            back.setVisible(false);
        }else if(n == 2){
            Page1.setVisible(false);
            Page2.setVisible(true);
            Page3.setVisible(false);
            Page4.setVisible(false);
            Page5.setVisible(false);
            
            cancel.setText("Cancel");
            next.setText("Next");
            back.setText("Back");
            
            cancel.setVisible(true);
            next.setVisible(true);
            back.setVisible(true);
        }else if(n%5 == 3){
            Page1.setVisible(false);
            Page2.setVisible(false);
            Page3.setVisible(true);
            Page4.setVisible(false);
            Page5.setVisible(false);
            
            cancel.setText("Cancel");
            next.setText("Install");
            back.setText("Back");
            
            cancel.setVisible(true);
            next.setVisible(true);
            back.setVisible(true);
        }else if(n%5 == 4){
            Page1.setVisible(false);
            Page2.setVisible(false);
            Page3.setVisible(false);
            Page4.setVisible(true);
            Page5.setVisible(false);
            
            cancel.setVisible(false);
            next.setVisible(false);
            back.setVisible(false);
        }else{
            Page1.setVisible(false);
            Page2.setVisible(false);
            Page3.setVisible(false);
            Page4.setVisible(false);
            Page5.setVisible(true);
            
            cancel.setText("Cancel");
            next.setText("Finish");
            back.setText("Back");
            
            cancel.setVisible(false);
            next.setVisible(true);
            back.setVisible(false);
            
        }
    }//GEN-LAST:event_backActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null,"Are you sure you want to exit?", "Confirm",JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION){
                exit(this);
            }
    }//GEN-LAST:event_cancelActionPerformed

    private void jCheckBoxEJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEJActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirmed = JOptionPane.showConfirmDialog(null,"Are you sure you want to exit?", "Confirm",JOptionPane.YES_NO_OPTION);
            if (confirmed == JOptionPane.YES_OPTION){
                exit(this);
            }
    }//GEN-LAST:event_formWindowClosing
    static void exit(JFrame j) {
               
                j.dispose();
    }
    
    static void runEXE(String url){
        String line;
        OutputStream stdin = null;
        InputStream stderr = null;
        InputStream stdout = null;
        Process process;
        try {
                    process = Runtime.getRuntime ().exec (url);
                    stdin = process.getOutputStream ();
                    stderr = process.getErrorStream ();
                    stdout = process.getInputStream ();

                    line = "param1" + "\n";
                    stdin.write(line.getBytes() );
                    stdin.flush();

                    line = "param2" + "\n";
                    stdin.write(line.getBytes() );
                    stdin.flush();

                    line = "param3" + "\n";
                    stdin.write(line.getBytes() );
                    stdin.flush();

                     stdin.close();

                    BufferedReader brCleanUp = new BufferedReader (new InputStreamReader (stdout));
                    while ((line = brCleanUp.readLine ()) != null) {
            
                    }
                    brCleanUp.close();

                    brCleanUp = new BufferedReader (new InputStreamReader (stderr));
                    while ((line = brCleanUp.readLine ()) != null) {

                    }
                    brCleanUp.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Installer.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Installer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Installer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Installer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Installer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
                    new Installer().setVisible(true);
                
}
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Page1;
    private javax.swing.JPanel Page2;
    private javax.swing.JPanel Page3;
    private javax.swing.JPanel Page4;
    private javax.swing.JPanel Page5;
    private javax.swing.JLayeredPane PageButton;
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JCheckBox jCheckBoxEJ;
    private javax.swing.JCheckBox jCheckBoxJDK;
    private javax.swing.JCheckBox jCheckBoxMysql;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
